name: Check Tests

on: 
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'pnp'
    name: "Test"
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      
      - name: Checkout SPFx Toolkit
        uses: actions/checkout@v4
        with:
          path: vscode-viva
        
      - name: Install dependencies for SPFx Toolkit
        run: npm install --omit=optional
        working-directory: vscode-viva

      - name: Build SPFx Toolkit
        run: npm run package
        working-directory: vscode-viva

      - name: Compile tests for SPFx Toolkit
        run: npm run compile-tests
        working-directory: vscode-viva

      - name: Run tests for SPFx Toolkit
        run: npm run test
        working-directory: vscode-viva
      
