name: Create .vsix package

on:
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'pnp'
    name: "Build and package"
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      
      - name: Checkout vscode-viva
        uses: actions/checkout@v4
        with:
          path: vscode-viva
        
      - name: Install the dependencies
        run: npm install --omit=optional
        working-directory: vscode-viva

      - name: Package
        run: |
          npx @vscode/vsce@3.3.2 package
        working-directory: vscode-viva

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vsix_package
          path: |
            vscode-viva/*.vsix
