name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: "Build and release"
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      
      - name: Checkout vscode-viva
        uses: actions/checkout@v4
        with:
          path: vscode-viva
        
      - name: Install the dependencies
        run: npm ci
        working-directory: vscode-viva

      - name: Checkout cli-microsoft365
        uses: actions/checkout@v4
        with:
          repository: Adam-it/cli-microsoft365
          path: cli-microsoft365
          ref: cli-cjs

      - name: Print dir
        run: |
          dir

      - name: Restore dependencies for cli-microsoft365
        run: npm i
        working-directory: cli-microsoft365

      - name: Build cli-microsoft365
        run: npm run build
        working-directory: cli-microsoft365

      - name: Run script copy local CLI for M365    
        run: .\vscode-viva\scripts\cli-for-microsoft365-copy-local-version.ps1 -workspacePath "${{ github.workspace }}"
        shell: pwsh
        continue-on-error: false

      - name: Publish
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}
        working-directory: vscode-viva