name: Pre-Release

on:
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'pnp'
    name: "Build and pre-release"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read
    
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      
      - name: Checkout vscode-viva
        uses: actions/checkout@v4
        with:
          path: vscode-viva
        
      - name: Install the dependencies
        run: npm install --omit=optional
        working-directory: vscode-viva

      - name: Publish 
        run: npx @vscode/vsce@3.3.2 publish -p ${{ secrets.VSCE_PAT }} --pre-release --baseImagesUrl https://raw.githubusercontent.com/pnp/vscode-viva/dev
        working-directory: vscode-viva
